spring:
    application:
        name:
            time-auction
    data:
        redis:
            host: localhost
            port: 6379
            # password: ""       # 필요 없으면 생략
            # database: 0
