spring:
  application:
    name:
      time-auction
  session:
    store-type: redis
  data:
    redis:
      host: localhost
      port: 6379
      # password: your_redis_password
  devtools:
    livereload:
      enabled: true

server:
  port: 8080